name: Build my shitty game

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up G++
      run: |
        sudo apt-get update
        sudo apt-get install gcc
      shell: bash
    
    - name: Install MAKE
      run: |
       sudo apt-get install make

    - name: Compile with MAKE
      run: make
    
    - name: OOOOOOOMAGA
      uses: actions/upload-artifact@v2
      with:
        name: shit
        path: ./multiverse_shit