name: Build my shitty game

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GCC and CSFML dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc
        sudo apt-get install libcsfml-dev
        sudo apt-get install libsfml-dev
      shell: bash
      
    - name: Compile for Linux and Windows
      run: ./build-both.sh
    
    - name: OOOOOOOMAGA
      uses: actions/upload-artifact@v2
      with:
        name: shit
        path: ./distr/mcards
