name: Build my shitty game

on:
  workflow_dispatch:

jobs:
  build:
    name: Buildagem
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GCC and CSFML dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc
        sudo apt-get install libcsfml-dev
        sudo apt-get install libsfml-dev
      shell: bash
      
    - name: Compile for Linux and Windows
      run: ./build-both.sh || true
    
    - name: OOOOOOOMAGA
      uses: actions/upload-artifact@v4
      with:
        name: shit-1
        path: ./distr

