name: mcards-build-workflow

on: workflow_dispatch

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout-code
        uses: actions/checkout@v5.0.0

      - name: install-and-setup-python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.10.12'

      - name: install-and-setup-dependencies
        run: |
         python --version
         sudo apt-get install -y git unzip openjdk-17-jdk autoconf libtool libtool-bin pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
         python -m venv .venv
         source .venv/bin/activate
         pip install pygame-ce
         pip install cython
         pip install kivy
         pip install buildozer

      - name: build-mcards
        run: |
         source .venv/bin/activate
         printf "y\ny\nn\ny\n" | buildozer android debug

      - name: upload-apk
        uses: actions/upload-artifact@v4.6.2
        with:
          name: mcards-build
          path: bin/*.apk # Para fins de garantia.
